### ISSUE TITLE
Maximum nodes per move support

### ISSUE THREAD

**Issue by Alayan-stk-2** [Matthies/RubiChess#117]
I wanted to test scaling with node count of a few engines to compare with SF. I'm running a cutechess tournament with a cutechess-cli option to limit nodes for an engine.

However, whereas SF results are natural (I'm running from 4^3 nodes to 4^8 nodes, and 4^3 scores worse than 4^4 which scores worse than 4^5 etc. with hundreds of elo of difference), Rubichess are not.

Rubichess 65K nodes doesn't perform clearly better than Rubichess 64 nodes:
```
   8 RubiChess_16384n               -5      69      71   49.3%   28.2%
   9 RubiChess_1024n                -5      69      71   49.3%   28.2%
  10 RubiChess_64n                 -19      68      72   47.2%   30.6%
  11 RubiChess_4096n               -24      67      72   46.5%   31.9%
  12 RubiChess_65536n              -44      73      71   43.7%   22.5%
  13 RubiChess_256n                -76      75      70   39.3%   21.4%
```

For comparison : 
```
   7 Stockfish_65536n              163      77      73   71.9%   23.3%
  14 Stockfish_16384n              -96      77      74   36.5%   13.5%
  15 Stockfish_4096n              -224      99      74   21.6%    2.7%
  16 Stockfish_1024n              -343     138      74   12.2%    0.0%
  17 Stockfish_256n               -522     417      74    4.7%    1.4%
  18 Stockfish_64n                -583     nan      74    3.4%    1.4%
```

It makes no sense to assume that 1000x the nodes don't improve the playing strength, so I assume the engine ignore the node limiting command that cutechess sends it ?

**Comment by Matthies** [comment]
You are right. The nodes parameter isn't implemented yet in RubiChess. But I will do now that it is needed :-)
Can you provide the exact commandline you (you script) uses for cutechess-cli? If RubiChess just gets a
go nodes <n>
command it should behave like
go [infinite]
and lose every game on time.

**Comment by Matthies** [comment]
nodes is now implemented with #118

**Comment by Alayan-stk-2** [comment]
Thank you, this was quick.

I'll test it and report back here tomorrow.

**Comment by Alayan-stk-2** [comment]
It doesn't work completely as expected. I think that's because it won't stop immediately on the exact node count. This is probably negligible for higher node counts, but it's noticeable for very low values.

```
   1 RubiChess_8192n               395      77     204   90.7%    6.9%
   2 RubiChess_4096n               245      56     204   80.4%   10.8%
   3 RubiChess_2048n                86      48     205   62.2%    6.3%
   4 Stockfish_1024n                24      46     205   53.4%    8.3%
   5 RubiChess_256n                 19      46     204   52.7%    8.3%
   6 RubiChess_1024n                 7      45     205   51.0%   11.2%
   7 RubiChess_512n                 -2      45     205   49.8%   10.7%
   8 RubiChess_128n                 -7      46     205   49.0%    7.3%
   9 RubiChess_32n                 -17      46     204   47.5%    8.8%
```

**Comment by Matthies** [comment]
You are right. I wanted to avoid too many time consuming checks at every node count, the "stop" is sent from the asynchron UCI input thread. I will take a look how other engines are doing it and maybe come back with a better solution.

**Comment by Alayan-stk-2** [comment]
I'll let it up to you to change this beahvior.

Here are my test results as promised. Stockfish is from May 9th, RubiChess from your nodes patch? The SF version with TM has been roughly aligned to its bullet fastgm rating. I used 8moves_v3 random openings for the test and the elo calculations are done with ordo.

I hope you'll find the data about RubiChess scaling interesting even if the sample size isn't huge. At 1K node it is roughly on par with SF (though the async stop may distort things a bit), but at 1M nodes it's on par with 80K nodes SF.

It gains 1400 elo from 4K nodes to 4M nodes (using default settings in ordo, and subject to some variance due to sss and the pool of configurations that each config was matched with).

```
    PLAYER                 :  RATING  POINTS  PLAYED   (%)

   1 Stockfish_67108864n    :  3731.6    34.0      50    68
   2 Stockfish_33554432n    :  3691.3    31.0      50    62
   3 Stockfish_16777216n    :  3683.9   136.5     200    68
   4 Stockfish_8388608n     :  3620.1   115.5     200    58
   5 Stockfish_4194304n     :  3517.5   765.5    1100    70
   6 Stockfish_TM (50+0.5)  :  3467.0   337.5     500    68
   7 Stockfish_2097152n     :  3429.3   630.0    1100    57
   8 Stockfish_1048576n     :  3328.7   626.0    1100    57
   9 Stockfish_524288n      :  3216.4  2240.5    3092    72
  10 Stockfish_262144n      :  3085.1  1851.0    3092    60
  11 RubiChess_4194304n     :  2979.3   365.5     500    73
  12 Stockfish_131072n      :  2904.3  1624.5    2692    60
  13 RubiChess_2097152n     :  2883.6   296.0     500    59
  14 RubiChess_1048576n     :  2790.1   702.5    1100    64
  15 Stockfish_65536n       :  2723.3  2734.5    4692    58
  16 RubiChess_524288n      :  2663.5  1659.0    2500    66
  17 RubiChess_262144n      :  2553.5  1300.5    2000    65
  18 Stockfish_32768n       :  2530.4  4886.5    6692    73
  19 RubiChess_131072n      :  2409.4   987.5    2000    49
  20 Stockfish_16384n       :  2299.0  4124.5    6692    62
  21 RubiChess_65536n       :  2269.7   696.0    2000    35
  22 RubiChess_32768n       :  2116.9  3453.0    4900    70
  23 Stockfish_8192n        :  2046.0  6653.0    9400    71
  24 RubiChess_16384n       :  1938.4  2731.0    4900    56
  25 Stockfish_4096n        :  1804.7  2979.5    4500    66
  26 RubiChess_8192n        :  1749.2  1941.0    3500    55
  27 RubiChess_4096n        :  1577.8  1349.5    3500    39
  28 Stockfish_2048n        :  1565.7  2448.5    4500    54
  29 RubiChess_2048n        :  1457.1   931.5    3500    27
  30 RubiChess_1024n        :  1395.1   728.0    3500    21
  31 Stockfish_1024n        :  1336.4  2420.0    8000    30
  32 Stockfish_512n         :  1141.8  1293.5    4500    29
  33 Stockfish_256n         :  1018.8   902.5    4500    20
  34 Stockfish_128n         :   949.9   690.0    4500    15
  35 Stockfish_64n          :   887.5   511.0    4500    11
```
