### ISSUE TITLE
Raspberry Pi compile failure:

### ISSUE THREAD

**Issue by ScallyBag** [Matthies/RubiChess#144]
Hi,

I’ve never had a problem before, however with your latest code, my Raspberry Pi 3b+ Compile fails:

Al@PicoChess:~/rubiChess/RubiChess $ make -j4
g++ -g -std=c++11 -Wall -O3 -flto   -march=armv7-a *.cpp -pthread    -o RubiChess
In file included from tbprobe.cpp:39:0:
tbcore.c: In function ‘int open_tb(const char*, const char*)’:
tbcore.c:67:28: error: ‘strcpy_s’ was not declared in this scope
     strcpy_s(file, paths[i]);
                            ^
tbcore.c:68:23: error: ‘strcat_s’ was not declared in this scope
     strcat_s(file, "/");
                       ^
tbcore.c: In function ‘void init_tablebases(char*)’:
tbcore.c:301:29: error: ‘strcpy_s’ was not declared in this scope
   strcpy_s(path_string, l, p);
                             ^
Makefile:27: recipe for target 'RubiChess' failed
make: *** [RubiChess] Error 1
Al@PicoChess:~/rubiChess/RubiChess $ 

Thanks,

Alan Cooper

**Comment by Matthies** [comment]
Thanks for the report. Should be fixed with latest master.

**Comment by ScallyBag** [comment]
It compiles without error now

Thanks,

Al.
