### ISSUE TITLE
integer overflow in tbcore.c

### ISSUE THREAD

**Issue by HansLoehle** [Matthies/RubiChess#160]
This type of error can happen easily and is simple to remove. I suggest `long f = j;` in line 559.

https://github.com/Matthies/RubiChess/blob/2e642b2bb0e012b67bf550346d6fcbcb86ecf040/RubiChess/tbcore.c#L562

Thank you for this strong chess engine!
Hans

**Comment by Matthies** [comment]
Can you describe how to reproduce the Problem? Which tablebase files do you use and which Position triggers the problem? Knowing this makes it easier to test the fix for me.

**Comment by Matthies** [comment]
Hmm. I had a closer look now but I don't understand the problem. You get a compiler warning? Both int and long should be 32bit at least with all compilers I am using. Do you compile for a different platform? Other than x86-64 or ARM64?

**Comment by HansLoehle** [comment]
32 bit are not enough. The worst case: For i==5 and j==63 f should hold the value 
`63 * 62 * 61 * 60 * 59 * 58 == 24 861 377 520 > 2^34`
To avoid negative binomial coefficients, I changed the initialisation of the array to:
```
// Alternative ohne Multiplikation:
memset(binomial, 0, sizeof(binomial));
for (i = 0; i < 64; i++)  binomial[0][i] = i;
  for (i = 0; i < 5; i++) {
    for (j = i; j < 63; j++) {
      binomial[i + 1][j + 1] = binomial[i][j] + binomial[i + 1][j];
    }
  }

```
which uses a well known recursive definition.

Due to curiosity I compiled the code with g++ -fsanitize=address,undefined *.cpp -pthread -lm -o rubisan
running rubisan discovered (among other issues): 

> signed integer overflow: 69090840 * 34 cannot be represented in type 'int'

Neither g++ nor clang++ or cppcheck discovered this.

The other issues had no effect (so far) on the program's behaviour and are related to `delete` operator and `new[]` (use `delete[]`)  or `malloc` (use `free` or `new` in place of `malloc`).

**Comment by Matthies** [comment]
Okay. You suggested to use "long" as a fix, that confused me. So I have to use "long long" which is 64bit.
And do we know if the overflown values are used in any tb access?
However, I will probably use your suggested fix.

**Comment by Matthies** [comment]
Should be fixed now in master.

**Comment by HansLoehle** [comment]
> Okay. You suggested to use "long" as a fix, that confused me. So I have to use "long long" which is 64bit.

Well, I mixed that. Sorry for any confusion.

> And do we know if the overflown values are used in any tb access?

Until now I did no investigation on the tb code. This is still on my 'Could Do List' ;)

> However, I will probably use your suggested fix.
