### ISSUE TITLE
RubiChess Playing Chess Variants, Musketeer Chess

### ISSUE THREAD

**Issue by musketeerchess** [Matthies/RubiChess#173]
Hi
It'll be nice to see your engine compete in the future Musketeer Chess tournaments that i'm organising.

Some interesting issues and repositories can be found here:

http://talkchess.com/forum3/viewtopic.php?f=7&t=72572&start=10#p822789

https://github.com/ianfab/Musketeer-Stockfish/issues/3

Best regards

Dr HADDAD
www.musketeerchess.net

**Comment by Matthies** [comment]
Currently I have no interest in supporting chess variants and especially no interest in getting involved in tournaments with prize money. Reading in talkchess engine origin forum I learned that money destroys the fun.

**Comment by musketeerchess** [comment]
Hi Matthies
Talking about money regards the sums involved (small amounts) is to attract people and  thank the participants.

I work now with 4 programmers and 3 of them don’t want money. Its fine for me. I thank them for their time and involvement.

This could be your case also.

Best regards
Zied

Welcome to Musketeer Chess, the next Chess Evolution
