### ISSUE TITLE
RubiChess 1.6.1.1für win64-bit ohe bmi2-Option (popcnt ist ok)

### ISSUE THREAD

**Issue by yellow-panther** [Matthies/RubiChess#176]
Hallo Matthies,

besteht die Möglichkeit, eine Windows.exe-Datei hochzuladen ? bmi2 vgl https://de.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

Gruß,

**Comment by Matthies** [comment]
Erledigt. bmi2 code verwende ich eh nicht, es gibt immer eine Version mit Hardware-popcount und eine ohne (-oldcpu).

**Comment by yellow-panther** [comment]
ja, ich heiße Norbert aus www.talkchess.com und mein Nick ist "yellow panther"
