### ISSUE TITLE
rubichess playing chess variants, Musketeer Chess

### ISSUE THREAD

**Issue by musketeerchess** [Matthies/RubiChess#189]
Hi Matthies
Nice work here.
I'm Dr Haddad, anesthesiologist living in France, currently in front line struggling with the Covid-19 infected patients. I'm a big chess fun and chess variant inventor.

I invented Musketeer Chess. You can find useful informations here:

Musketeer-Stockfish; engine playing Musketeer Chess here: https://github.com/ianfab/Musketeer-Stockfish
Rules here: https://github.com/fsmosca/musketeer-chess

and some interesting discussions here about using Winboard / XBoard as a GUI: https://github.com/ianfab/Musketeer-Stockfish/issues
http://talkchess.com/forum3/viewtopic.php?f=7&t=72572

I'll be glad and very happy if you join.

Please feel free to email me to musketeerchess (a) gmail .com

Best regards
Zied

**Comment by Matthies** [comment]
Duplicate to #173 and it makes no difference that you are "struggling with the Covid-19 infected patients".
