### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by AlexB123** [Matthies/RubiChess#199]
Hello! I would like to report a couple issues regarding Android compilations.
1) Please change lines 21 and 170 in transposition.cpp, to 
#if defined(__linux__) && !defined(__ANDROID__)

2) Something is wrong in current 1.7.1. I'm not able to compile android engines using NDK's Clang on Windows, i'm getting the follow errors.
![Rubi](https://user-images.githubusercontent.com/19660133/79860927-372d9780-83dc-11ea-8d86-104c9e7888e9.jpg)

**Comment by Matthies** [comment]
Cool. I was not aware that this code is (almost) ready for Android. I will do some commits in a few moments and you can test again. And I will probably setup this Android NDK later so I can test myself.

**Comment by Matthies** [comment]
Master has some fallback malloc for Android now. Please test again.

**Comment by AlexB123** [comment]
> 
> 
> Master has some fallback malloc for Android now. Please test again.

Hi! From your last source code. The issue is still there.
![Rubi test 2](https://user-images.githubusercontent.com/19660133/79924725-43980b80-8441-11ea-91bd-6f123248f9f8.jpg)

**Comment by Matthies** [comment]
Hmm. Strange.
```
#ifdef ANDROID
#define allocalign64(x) malloc(x)
#define freealigned64(x) free(x)
#else
#define allocalign64(x) aligned_alloc(64, x)
#define freealigned64(x) free(x)
#endif
```
Seems that the #ifdef ANDROID doesn't work here. Are you sure this ANDROID is the correct define to check for?

**Comment by Matthies** [comment]
Stockfish uses __ANDROID__ to test for Android compilation. Can you try this change in your local source and report if it works. I still haven't setup any Android development environment.

**Comment by AlexB123** [comment]
> 
> 
> Stockfish uses `__ANDROID__` to test for Android compilation. Can you try latest master again and report if it works. I still haven't setup any Android development environment. And I just noticed that Github changes the underscores to some bold font as we can see them in your first report :-)

Nope. Still not working.
![Rubi test 3](https://user-images.githubusercontent.com/19660133/80026662-2d468a00-84eb-11ea-8dc3-6ca50b98c261.jpg)

**Comment by AlexB123** [comment]
I checked the older code, the last "working" one is Ttinqs (#194) https://github.com/Matthies/RubiChess/commit/bddd8b8098972df1a96f2e42a79489e78f211964
![Rubi older working](https://user-images.githubusercontent.com/19660133/80026960-acd45900-84eb-11ea-95ae-d6e6f7ce50dc.jpg)
The problem appeared in the next update Eval (#195) https://github.com/Matthies/RubiChess/commit/bd9d640603838bd5dcba6689b96cbf8f22434306
![Rubi issue older](https://user-images.githubusercontent.com/19660133/80027316-3dab3480-84ec-11ea-9064-f8be20da58bb.jpg)
It started with "malloc" and later affected to "HashAlignBytes" and "MADV_HUGEPAGE".

**Comment by Matthies** [comment]
I hope that this works now finally. Can you describe in short words how to setup the Android environment? I have installed the NDK but I probably need some more tools or at least set some environment variables to find the correct libs?

**Comment by AlexB123** [comment]
> 
> 
> I hope that this works now finally. Can you describe in short words how to setup the Android environment? I have installed the NDK but I probably need some more tools or at least set some environment variables to find the correct libs?

Thanks, now it works! Regarding NDK, there is no short description of how it works. :-) You will need to generate android-toolchain for arm7 (32bit) and arm8 (64bit) engines, with appropriate API level for each, separately. After that you'll need to create a batch file, where you have to set paths to android-toolchains and all the necessary flags for android compiles..

**Comment by Matthies** [comment]
Okay. So I leave the Android stuff for the experts and close here.

**Comment by Matthies** [comment]
@AlexB123 Can you test current master if it compiles for Android? I will release soon and it would be good to check if it is ready for Android.

**Comment by AlexB123** [comment]
> 
> 
> @AlexB123 Can you test current master if it compiles for Android? I will release soon and it would be good to check if it is ready for Android.

Hi, sorry for delay with the answer. Yes, engine compiles fine, without any problems. Used source code from here https://github.com/Matthies/RubiChess/commit/26fa0c665c50f0c81538289feddae06de38b2f1a
