### ISSUE TITLE
4b3/8/3b1p2/2p2Bp1/1kPpPpP1/3P4/3K4/4N3 b - - 39 108 

### ISSUE THREAD

**Issue by Matthies** [Matthies/RubiChess#219]
Just noticed in some game that Rubi doesn't find winning move f3 and pasted it to the issue tracker.

**Comment by unaiic** [comment]
Is that a FEN position Rubi does not evaluate properly?

**Comment by unaiic** [comment]
It is interesting that after 108...f3 and 109.Nxf3 (FEN: 4b3/8/3b1p2/2p2Bp1/1kPpP1P1/3P1N2/3K4/8 b - - 0 109), RubiChess does immediately see the "main line" move 109...Bf4+ (even the alternative 109...Ba4 as a second option), but does not consider 108...f3 as a good move at first (prefering 108...Be5 or 108...Kb3). Maybe it has something to do with mobility/move which gives check or something similar; I will take a look, though.
