### ISSUE TITLE
Windows Defender False Positive

### ISSUE THREAD

**Issue by Vapenord** [Matthies/RubiChess#256]
Windows Defender identifies "Trojan:Win32/Meterpreter.A" when trying to download new Rubi 1.9
Surely a false positive but might want to look into it.

**Comment by Matthies** [comment]
Also noticed it yesterday.
Checked the zip at virustotal.com and Microsoft scanner is the only one of 64 scanners that detects a virus. So obviously false.
Will let this issue open for retesting later...

**Comment by Matthies** [comment]
Uploaded new zip Windows-stable-binaries-1.9-new using a more agressive compression rate to the release. Hope this will work around the false-positive.

**Comment by Matthies** [comment]
Microsoft call was closed with "no virus detected". Ray Banks reports that the problem is gone after Defender updated definition file: http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=12571&sid=f49502e536a8c18ceb0037fbb639624c
