### ISSUE TITLE
There are identical sub-expressions to the left and to the right of the && operator

### ISSUE THREAD

**Issue by thehlopster** [Matthies/RubiChess#269]
The `&&` operator is surrounded by identical subexpressions `TB_hash[hashIdx].key`
https://github.com/Matthies/RubiChess/blob/a3cb25932d109938e7c50fd669a2f77ebcb22e25/src/tbprobe.cpp#L220
looks like a typo and probably should be replaced with
```cpp
while (TB_hash[hashIdx].key && TB_hash[hashIdx].key != key) 
```

**Comment by Matthies** [comment]
Fixed directly in master. Thank you.
