### ISSUE TITLE
Kingdanger

### ISSUE THREAD

**Issue by Matthies** [Matthies/RubiChess#278]
TCEC Swiss-1: Rubi doesn't see sac 14. Bxh7+ and the following kingdanger.

[Event "TCEC Season 20 - Swiss 1"]
[Site "https://tcec-chess.com"]
[Date "2021.03.21"]
[Round "1.35"]
[White "Pedone 3.0"]
[Black "RubiChess 2.0.1"]
[Result "1-0"]
[Annotator "archive"]

1. e4 c5 2. Nf3 Nc6 3. d4 cxd4 4. Nxd4 Qb6 5. Nb3 Nf6 6. Nc3 e6 7. Bd3 Be7 8. Be3 Qc7 9. f4 O-O 10. g4 d5 11. e5 Nd7 12. Nb5 Qd8 13. g5 Nb4 14. Bxh7+ Kxh7 15. Qh5+ Kg8 16. O-O Re8 17. Rf3 g6 18. Qh4 Bf8 19. Rh3 Bg7 20. Qh7+ Kf8 21. N3d4 Nc6 22. Nd6 Qe7 23. Qh8+ Bxh8 24. Rxh8+ Kg7 25. Rxe8 Nb6 26. Rxe7 Nxe7 27. b3 Bd7 28. Nxb7 Rb8 29. Nd6 Kg8 30. Nf3 Kg7 31. h4 Nbc8 32. Kf2 a5 33. Bc5 Nc6 34. a3 N8e7 35. Rh1 Ra8 36. Nh2 Nf5 37. Ng4 Nce7 38. Nf6 Bc6 39. h5 gxh5 40. Rxh5 Kg6 41. Rh7 Nxd6 42. exd6 Nf5 43. Rh3 Rd8 44. d7 a4 45. Bb6 Rxd7 46. Nxd7 Bxd7 47. Bc7 d4 48. b4 Bb5 49. Be5 Bd7 50. Rh8 Bc6 51. Rg8+ Kh5 52. Rd8 Kg4 53. Rf8 Kh5 54. Rxf7 Be8 55. Rf8 Bc6 56. Rc8 Be4 57. b5 Kg6 58. b6 Nh4 59. Rc7 Nf5 60. b7 Bxb7 61. Rxb7 Kh5 62. Rf7 Kg6 63. Rf6+ Kh7 64. g6+ Kg7 65. Rxf5+ Kxg6 66. Rf8 d3 67. cxd3 Kh7 68. Kf3 Kh6 69. f5 exf5 70. Kf4 Kg6 71. Bb2 Kh5 72. Rf6 Kh4 73. Rh6#
*

**Comment by Matthies** [comment]
New net nn-cf8c56d366-20210326.nnue finds Bxh7+ at depth 43 (23 minutes on my Intel core i5-4590 1 thread 1024MB Hash). No idea if this would have been enough on the TCEC hardware.

**Comment by tissatussa** [comment]
This is a very nice Greek Gift position ! (after 13...Nb4)

![Screenshot_2021-04-12_21-29-50](https://user-images.githubusercontent.com/1109281/114546023-fc5fe780-9c5c-11eb-95d8-f660d3ac7b4b.png)

White to move.  I did several tests in this position.  I have many engines and Pedone seems the only (!?) one which immediately (!) finds 14.Bxh7 best move and thus wins against many strong engines, including the new SF 13 .. but against RubiChess v2.1-dev it looses, see this game :

```
[Event "engine vs engine"]
[Site "?"]
[Date "2021.04.13"]
[White "Pedone v3.0 NN"]
[Black "RubiChess v2.1-dev NNUE"]
[Result "0-1"]
[GameDuration "00:33:09"]
[PlyCount "94"]
[SetUp "1"]
[TimeControl "900+5"]
[FEN "r1bq1rk1/pp1nbppp/4p3/1N1pP1P1/1n3P2/1N1BB3/PPP4P/R2QK2R w KQ - 0 14"]

14. Bxh7+ Kxh7 15. Qh5+ Kg8 16. O-O g6 17. Qh4 Re8 18. Rf3 Bf8 19. Rh3 Bg7 20. Qh7+ Kf8 21. N3d4 Nc6 22. Nd6 Ne7 23. Rh6 Nb6 24. b3 Bd7 25. Rf1 Qc7 26. Rf3 Qc3 27. h4 Nc6 28. N4b5 Qxc2 29. Nxf7 Ne7 30. Nh8 Qd1+ 31. Kg2 Bxb5 32. Bc5 Qc2+ 33. Rf2 Qxc5 34. Nxg6+ Nxg6 35. Rxg6 Re7 36. f5 Bd3 37. f6 Be4+ 38. Rf3 Bxf3+ 39. Kxf3 Qc3+ 40. Kf2 Qd4+ 41. Kf1 Qf4+ 42. Kg1 Qe3+ 43. Kf1 Qf3+ 44. Kg1 Qg4+ 45. Kh2 Qe2+ 46. Kg1 Qe1+ 47. Kg2 Qe4+ 48. Kg1 Rf7 49. Rh6 Qxh7 50. Rxh7 Bxf6 51. Rh6 Bxe5 52. Kg2 Rc8 53. Rxe6 Nd7 54. b4 Rc3 55. Rf6 Nxf6 56. g6 Nh5 57. gxf7 Nf4+ 58. Kf1 Bd4 59. Ke1 Be3 60. h5 Rc1# 0-1
```

RubiChess v2.1-dev deviates from your game at move 22 : it plays not Qe7 but Ne7 and .. wins !

**Comment by Matthies** [comment]
32. Bc5 is really bad move from Pedone and it switches back to better move Kxg6+ at depth 26 here so this blunder would probably not happen at TCEC. Anyway... seems that new Rubi can deal a little better with this position. Thanks for investigation.

**Comment by Matthies** [comment]
Moved to #304
