### ISSUE TITLE
Illegal move (from last position)

### ISSUE THREAD

**Issue by Matthies** [Matthies/RubiChess#3]
In some rare cases (~one of 1000 cutechess games) the search seems to end immediately and outputs the bestmove from the search before which is illegal. Time control seems not relevant as it occures even in 60000 + 600 startposition.

**Comment by Matthies** [comment]
Fixed by some commit... I don't remember.

**Comment by Spill-The-Tea** [comment]
I am running into the same issue on cutechess (TC = 40/1.0+0.01), but much more frequently than you are reporting. I checked in the beginning of the match, and I had about 12 instances out of 40 total games played where this exact scenario happened.
