### ISSUE TITLE
Time management query

### ISSUE THREAD

**Issue by eskstrand10** [Matthies/RubiChess#314]
Rubichess is using maximum of 1/3rd of allowed time per move, see attached txt files
rubi test 1-10: rubi 2.2 vs Xiphos 6.1 1 minute and 10 sec/per move
rubi test 1-3: rubi 2.2 vs Xiphos 6.1 1 minute and 3 sec/per move

Settings for Rubi are 4 threads, 1024 Hash, opening book off, ponder off, NNUE on, large pages off, avx2 binary used
Xiphos using same 4 threads, 1024 hash, ponder off
Book is at max 3 moves deep
Cutechess used

[rubi test 1-10.txt](https://github.com/Matthies/RubiChess/files/7621021/rubi.test.1-10.txt)
[rubi test 1-3.txt](https://github.com/Matthies/RubiChess/files/7621026/rubi.test.1-3.txt)

Is the time management correct?

**Comment by Matthies** [comment]
Okay, I can reproduce. You are using the (quite exotic) timecontrol "time for n moves with additional increment". Rubi doesn't use the increment and tries to press all the 500 moves into one minute. Will fix...

**Comment by Matthies** [comment]
The bug should be fixed now in current master. If you don't want to wait for new Windows binary, you can workaround the bug by setting Moves to "Whole game" in the cutechess time control GUI which is probably what you want when you set it to 500 before.

**Comment by eskstrand10** [comment]
Thanks for fixing, I will try and and use more normal settings as well
