### ISSUE TITLE
Using RubiChess in a film

### ISSUE THREAD

**Issue by emmasbergman** [Matthies/RubiChess#315]
Hello!
I am the Director’s Assistant for a small indie feature by Dustin Guy Defa. There is a scene in the film where the main character (Michael Cera) is playing chess on his computer. We are hoping to get your permission to display RubiChess on the character's computer screen. We would, of course, credit you for your work. Let me know what you think!
-Emma Bergman

**Comment by Matthies** [comment]
Would be a pleasure to see RubiChess in a film. I don't even want a fee for it :-D
You may drop a note here when the film is ready and can be seen somewhere.

**Comment by tissatussa** [comment]
Not to be rude, but when you display some chess program in a movie, why not pick the program called "Blunder" ?  This is the real name of a rather strong open source chess engine, see https://github.com/algerbrex/blunder . Wouldn't that be funny and intriguing !?
Btw. I have no connection to Blunder at all, but no "lack of imagination" : https://www.bitchute.com/video/fQcz6HI6PI2R/ :-)
