### ISSUE TITLE
Fix for OS X clang build error

### ISSUE THREAD

**Issue by tillchess** [Matthies/RubiChess#316]
Fix for OS X clang build error:

Put this in Rubichess.h

```

#if defined(__clang__)
# include <immintrin.h>
#endif

```

**Comment by Matthies** [comment]
Hmm. The include should already be there, at least for systems that support avx2.
Can you write something about your system and give the complete output of your "make" containing the error message? There should be some information about which CPU features are detected on your system.

**Comment by Matthies** [comment]
I see a problem now compiling with ARCH=x86-64-modern:
Undeclared identifier _tzcnt_u64 and _blsr_u64.

**Comment by tillchess** [comment]
The above fix should do it

**Comment by Matthies** [comment]
Maybe. But it is the wrong solution IMO. Hope to find a better one.

**Comment by tillchess** [comment]
My makefile output:

Compiler: clang
Arch: native
CPU features:
=============
avx512: no
bmi2  : no
avx2  : no
bmi1  : no
lzcnt : no
popcnt: yes
ssse3 : yes
sse2  : yes
neon  : no

Looking at your sources it's clear that for sse3 and sse2 for clang compiler on OS X.
you need #include <immintrin.h>

**Comment by Matthies** [comment]
Okay, this seems a little different from mine. Can you give me the exact error message(s) you get when compiling?

**Comment by Matthies** [comment]
Latest master should compile now in Mac OS. Would be nice if you can confirm.

**Comment by tillchess** [comment]
Geht!

**Comment by Matthies** [comment]
Na denn mach ich hier mal zu :-)
