### ISSUE TITLE
Unstable evaluation

### ISSUE THREAD

**Issue by Matthies** [Matthies/RubiChess#419]
With latest networks(?), the eval gets very unstable. Many fail low/fail high and visible e.g. in the first 40 moves of this game: https://tcec-chess.com/#div=cup12t&game=52&season=25

2n3k1/2b1RNp1/5pNp/p3p2P/1p2P3/1P4PK/P1r2P2/8 w - - 3 50 is an example for a position that shows extreme eval jumps and seeing white winning which is wrong.
![grafik](https://github.com/Matthies/RubiChess/assets/3756180/65a63bb5-f7e8-4744-ba19-313170ea7412)

Maybe some pruning margins need to be tuned. Or some problem with qsearch?

**Comment by ChessOverflow** [comment]
Probably this problem occurs because of the `extension`. Maybe "Check extension" or Another extension!

**Comment by ChessOverflow** [comment]
So there is a 99% probability that this problem is related to the `margins`. 

Use the **Explode** [`multipv = 99`] and see if this problem happens again? 

If happens again, probability the problem is not related to `margins`.

**Comment by ChessOverflow** [comment]
@Matthies Finally I found the answer of this question. This is not an issue. See this picture:

![paints](https://github.com/Matthies/RubiChess/assets/137254056/80861c7b-b508-4be5-8994-8bea8d43ba32)

Score cp +3.45 is correct but It's not means that White is winning , this is very heavy positions.

**Comment by ChessOverflow** [comment]
> and has nothing to do with the issue.

This is the continuation of your position

**50. Nxh6+ gxh6 51. Re8+ Kf7 52. Rxc8 Ke6 53. Rh8 Rxa2 54. Rxh6 a4 55. bxa4 Rxf2
56. Rh7 Kd6 57. Nf8 Kc6 58. Ne6 Bb6 59. Rh8 b3 60. Rc8+ Kd6 61. Rb8 Ba7 62. Rxb3
Kxe6 63. h6 Rf1 64. Rb7 Bc5 65. h7 Rh1+ 66. Kg2 Rh6 67. a5 f5 68. Rc7 Bd6 69. a6
Bxc7 70. a7 Rxh7 {+1.54}**

>  Last warning: Stop trolling here. This issue is not meant to be discussed with you.

I will not help you any more, you made me very sad, goodbye
