### ISSUE TITLE
Illegal Move Generation (Resubmitting Previous Move?)

### ISSUE THREAD

**Issue by Spill-The-Tea** [Matthies/RubiChess#99]
Reviving an issue previously encountered, here: https://github.com/Matthies/RubiChess/issues/3

During Tournament Round Robin Matchups in cutechess (TC=40/1.0+0.01), Rubichess (1.3.1) frequently loses by Illegal Move Generation (specifically by resubmitting the previous move). I checked at the beginning of a tournament, and this happened 12 out of 40 games.

All of these events seem to occur near time control (moves 36-40), so this may have something to do with time management...

**Comment by Spill-The-Tea** [comment]
![RubiChess_Illegal_Moves](https://user-images.githubusercontent.com/44797905/54156409-6add7600-4403-11e9-851f-6048bb919f44.jpg)

Just a little graph, of the occurrence of Illegal Move generation. Each data point was performed in triplicate, with each tournament of 1000 games.

**Comment by Matthies** [comment]
You are using a quite uncommon timecontrol with both movenumber and increment. I must admit that I never tested this so chances are good that there is a bug in it. Will have a look. Maybe you can test if this also happens when you leave out increment and give it some more base time, e.g. 40/5.0

**Comment by Spill-The-Tea** [comment]
Yes. I used short, incremented time controls of 1.0s + (3-15ms) over 40 moves. By TC=40/1.0+0.015, I observe 0.17% games ending due to submission of an illegal move. This isn't really the problem.
The real problem is much more pronounced in matches without an increment (red dots in graph above):

TC = 40/ | Mean
-- | --
1.12 | 85.27%
1.20 | 84.13%
1.32 | 82.80%
2.00 | 77.77%
5.00 | 56.23%
10.00 | 23.20%
20.00 | 2.95%
50.00 | 0.00%

Here are the results for reference:
[RubiTest_Illegal move frequency.xlsx](https://github.com/Matthies/RubiChess/files/2955409/RubiTest_Illegal.move.frequency.xlsx)

**Comment by Matthies** [comment]
Okay.There might be problems with movestogo and short timecontrol in general. I do all my short timecontrol tests with fistest-like time+increment. My movestogo tests are 40/4 like, so at least 120s on a fast machine.
I will have a look. Probably just needs moveoverhead scaled by the movestogo number.

**Comment by Matthies** [comment]
The issue should be fixed in the branch "lowontime" now. I'm still testing this branch at normal/longer time control for regression which may take some time.
Are you able to compile a binary from the branch yourself? If not I could provide a binary here.

**Comment by Matthies** [comment]
Fixed by #101

**Comment by Spill-The-Tea** [comment]
Thank you Matthies.
Yes. I am able to compile the binary myself.
I'll test it out and get back to you to determine if the issue is resolved.

**Comment by Spill-The-Tea** [comment]
Hi Matthies,
Nice work.
I tested it twice at two short time controls, with and without an increment (TC=40/1.0 & TC=40/1.0+0.003), and didn't observe any illegal move generation over 10,000 games (for each).
